name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python scripts/testing_model.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy Streamlit App
      run: |
        pip install streamlit
        streamlit run app/streamlit_app.py --server.port 8501
